### ISSUE TITLE
while starting the enodo gui i get a export error

### ISSUE THREAD

**Issue by farhedge-beech** [SiriDB/siridb-enodo-gui#9]
Starting the development server...

Failed to compile.

./src/pages/Dashboard/index.js
Attempted import error: 'useHistory' is not exported from 'react-router-dom'.

**Comment by timoj** [comment]
@farhedge-beech 
Thanks for the feedback. This will be fixed when we push our changes from development into master. I think we will be able to do this today or tomorrow.

**Comment by timoj** [comment]
@farhedge-beech The master branch is updated, issue should be fixed. I am closing this issue for now.
